# site
title: Äggie Lee Pak Yee
baseurl: "/doodlin-archive"
url: "https://michaelbecken.github.io"
favicon: "/assets/images/ico.png"

# bio
header: Äggie Lee Pak Yee
desc: >
      李 柏 誼 <br>
      [Lei5 Paak3 Ji6]'s doodlin' archive <br><br>
      &#8617; <a href="http://www.itchyeggie.com">back to the main site!</a> 

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
